### ISSUE TITLE
Do usecase document in markdown instead of pdf to allow PR's

### ISSUE THREAD

**Issue by sparrell** [opencybersecurityalliance/documentation#19]
The usecase document is stored as a pdf (https://github.com/opencybersecurityalliance/documentation/blob/master/Architecture%20Documents/Use%20Cases%20for%20Open%20Cybersecurity%20Alliance%20v1.pdf). I would prefer documents, when possible, be stored in a form that comments and changes could be input with github tools. The typical way for text in github is to use markdown (eg for README.md)

**Comment by warrenrjwc** [comment]
Completed and posted
